name = "oDMRG"
uuid = "fcfafd5e-473f-4563-ada5-380eac50bb01"
authors = ["heitorc7 <heitorc.7@gmail.com>"]
version = "0.1.0"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"   
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"  # Stdlib UUID

[compat]
julia = "≥1.6"  # Required for stdlib handling